"use client";

import { Button } from "@heroui/button";
import { Spinner } from "@heroui/spinner";
import { Popover, PopoverTrigger, PopoverContent } from "@heroui/popover";
import { SparklesIcon } from "@/components/icons";
import { useAISummaryStore } from "@/lib/store/ai-summary-store";

interface AISummarySectionProps {
  schoolId: string;
  bsn: string;
}

export function AISummarySection({ schoolId, bsn }: AISummarySectionProps) {
  const { getSummary, isLoading: isSummaryLoading, getError: getSummaryError, fetchSummary } = useAISummaryStore();

  const handleSummarizeSchool = async () => {
    await fetchSummary({
      schoolId: schoolId,
      bsn: bsn,
    });
  };

  return (
    <div>
      <div className="flex items-center gap-2 mb-3">
        <SparklesIcon size={16} className="text-primary" />
        <span className="text-xs font-semibold text-foreground">
          AI-Powered School Summary
        </span>
        <Popover placement="top" showArrow>
          <PopoverTrigger>
            <button
              className="flex items-center justify-center w-4 h-4 rounded-full bg-default-200 hover:bg-default-300 transition-colors cursor-help"
              aria-label="Information about AI summary"
            >
              <span className="text-[10px] text-default-600 font-semibold">?</span>
            </button>
          </PopoverTrigger>
          <PopoverContent className="max-w-[280px]">
            <div className="px-3 py-2">
              <div className="text-xs font-semibold text-foreground mb-1">
                ⚠️ AI-Generated Content
              </div>
              <p className="text-xs text-default-600 leading-relaxed">
                This summary is generated by AI and may contain inaccuracies. Please
                verify important information directly with the school or visit their
                official website.
              </p>
            </div>
          </PopoverContent>
        </Popover>
      </div>

      {/* Summarize Button - Only show if no summary */}
      {!getSummary(bsn) && !getSummaryError(bsn) && (
        <Button
          size="sm"
          variant="solid"
          fullWidth
          startContent={
            isSummaryLoading(bsn) ? <Spinner size="sm" color="white" /> : <SparklesIcon size={16} />
          }
          onPress={handleSummarizeSchool}
          isDisabled={isSummaryLoading(bsn)}
          className="bg-gradient-to-r from-violet-600 via-purple-600 to-indigo-600 text-white font-semibold shadow-lg hover:shadow-xl transition-all duration-300 hover:scale-[1.02]"
          style={{
            background:
              "linear-gradient(135deg, #7c3aed 0%, #a855f7 50%, #6366f1 100%)",
          }}
        >
          {isSummaryLoading(bsn) ? "Summarizing..." : "Generate AI Summary"}
        </Button>
      )}

      {/* AI Summary Content */}
      {getSummaryError(bsn) && (
        <div className="p-3 rounded-lg bg-danger/10 border border-danger/20">
          <p className="text-xs text-danger">⚠️ {getSummaryError(bsn)}</p>
        </div>
      )}

      {getSummary(bsn) && (
        <div className="relative max-h-[200px] overflow-y-auto rounded-lg bg-gradient-to-br from-primary/5 to-primary/10 border border-primary/20 scrollbar-thin scrollbar-thumb-primary/30 scrollbar-track-transparent">
          <div className="p-3 text-xs text-default-700 leading-relaxed prose prose-sm max-w-none">
            <div
              dangerouslySetInnerHTML={{
                __html: getSummary(bsn)!
                  .replace(
                    /\*\*(.*?)\*\*/g,
                    '<strong class="text-foreground font-semibold">$1</strong>'
                  )
                  .replace(/^• /gm, '<span class="text-primary">•</span> ')
                  .replace(/\n/g, "<br />"),
              }}
            />
          </div>
          {/* Fade effect at bottom */}
          <div className="absolute bottom-0 left-0 right-0 h-6 bg-gradient-to-t from-primary/10 to-transparent pointer-events-none" />
        </div>
      )}
    </div>
  );
}

